### ISSUE TITLE
fix--vee-app--move to env right wp_siteurl var

### ISSUE THREAD

**Issue by DimaMinka** [cdk-comp/vagrant-easyengine#1]
https://github.com/cdk-comp/vagrant-easyengine/blob/master/vee-app.sh#L46

**Comment by Captain4eyes** [comment]
echo "WP_SITEURL=$``{WP_HOME}/wp" >> test;

**Comment by Captain4eyes** [comment]
1) echo "WP_SITEURL=$``{WP_HOME}/wp" >> $vee_tmp/.env
2) echo "WP_SITEURL=\\${WP_HOME}/wp" >> $vee_tmp/.env
